// Code generated by protoc-gen-go.
// source: types/types.proto
// DO NOT EDIT!

/*
Package types is a generated protocol buffer package.

It is generated from these files:
	types/types.proto

It has these top-level messages:
	Request
	RequestEcho
	RequestFlush
	RequestInfo
	RequestSetOption
	RequestAppendTx
	RequestCheckTx
	RequestQuery
	RequestProof
	RequestCommit
	RequestInitChain
	RequestBeginBlock
	RequestEndBlock
	Response
	ResponseException
	ResponseEcho
	ResponseFlush
	ResponseInfo
	ResponseSetOption
	ResponseAppendTx
	ResponseCheckTx
	ResponseQuery
	ResponseProof
	ResponseCommit
	ResponseInitChain
	ResponseBeginBlock
	ResponseEndBlock
	TMSPInfo
	LastBlockInfo
	ConfigInfo
	Header
	BlockID
	PartSetHeader
	Validator
*/
package types

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Not being used
// Could be added to request/response
// so we don't have to type switch
// (would be twice as fast, but we're talking about 15ns)
type MessageType int32

const (
	MessageType_NullMessage MessageType = 0
	MessageType_Echo        MessageType = 1
	MessageType_Flush       MessageType = 2
	MessageType_Info        MessageType = 3
	MessageType_SetOption   MessageType = 4
	MessageType_Exception   MessageType = 5
	MessageType_AppendTx    MessageType = 17
	MessageType_CheckTx     MessageType = 18
	MessageType_Commit      MessageType = 19
	MessageType_Query       MessageType = 20
	MessageType_InitChain   MessageType = 21
	MessageType_BeginBlock  MessageType = 22
	MessageType_EndBlock    MessageType = 23
	MessageType_Proof       MessageType = 24
)

var MessageType_name = map[int32]string{
	0:  "NullMessage",
	1:  "Echo",
	2:  "Flush",
	3:  "Info",
	4:  "SetOption",
	5:  "Exception",
	17: "AppendTx",
	18: "CheckTx",
	19: "Commit",
	20: "Query",
	21: "InitChain",
	22: "BeginBlock",
	23: "EndBlock",
	24: "Proof",
}
var MessageType_value = map[string]int32{
	"NullMessage": 0,
	"Echo":        1,
	"Flush":       2,
	"Info":        3,
	"SetOption":   4,
	"Exception":   5,
	"AppendTx":    17,
	"CheckTx":     18,
	"Commit":      19,
	"Query":       20,
	"InitChain":   21,
	"BeginBlock":  22,
	"EndBlock":    23,
	"Proof":       24,
}

func (x MessageType) String() string {
	return proto.EnumName(MessageType_name, int32(x))
}
func (MessageType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type CodeType int32

const (
	CodeType_OK CodeType = 0
	// General response codes, 0 ~ 99
	CodeType_InternalError     CodeType = 1
	CodeType_EncodingError     CodeType = 2
	CodeType_BadNonce          CodeType = 3
	CodeType_Unauthorized      CodeType = 4
	CodeType_InsufficientFunds CodeType = 5
	CodeType_UnknownRequest    CodeType = 6
	// Reserved for basecoin, 100 ~ 199
	CodeType_BaseDuplicateAddress     CodeType = 101
	CodeType_BaseEncodingError        CodeType = 102
	CodeType_BaseInsufficientFees     CodeType = 103
	CodeType_BaseInsufficientFunds    CodeType = 104
	CodeType_BaseInsufficientGasPrice CodeType = 105
	CodeType_BaseInvalidInput         CodeType = 106
	CodeType_BaseInvalidOutput        CodeType = 107
	CodeType_BaseInvalidPubKey        CodeType = 108
	CodeType_BaseInvalidSequence      CodeType = 109
	CodeType_BaseInvalidSignature     CodeType = 110
	CodeType_BaseUnknownAddress       CodeType = 111
	CodeType_BaseUnknownPubKey        CodeType = 112
	CodeType_BaseUnknownPlugin        CodeType = 113
	// Reserved for governance, 200 ~ 299
	CodeType_GovUnknownEntity      CodeType = 201
	CodeType_GovUnknownGroup       CodeType = 202
	CodeType_GovUnknownProposal    CodeType = 203
	CodeType_GovDuplicateGroup     CodeType = 204
	CodeType_GovDuplicateMember    CodeType = 205
	CodeType_GovDuplicateProposal  CodeType = 206
	CodeType_GovDuplicateVote      CodeType = 207
	CodeType_GovInvalidMember      CodeType = 208
	CodeType_GovInvalidVote        CodeType = 209
	CodeType_GovInvalidVotingPower CodeType = 210
)

var CodeType_name = map[int32]string{
	0:   "OK",
	1:   "InternalError",
	2:   "EncodingError",
	3:   "BadNonce",
	4:   "Unauthorized",
	5:   "InsufficientFunds",
	6:   "UnknownRequest",
	101: "BaseDuplicateAddress",
	102: "BaseEncodingError",
	103: "BaseInsufficientFees",
	104: "BaseInsufficientFunds",
	105: "BaseInsufficientGasPrice",
	106: "BaseInvalidInput",
	107: "BaseInvalidOutput",
	108: "BaseInvalidPubKey",
	109: "BaseInvalidSequence",
	110: "BaseInvalidSignature",
	111: "BaseUnknownAddress",
	112: "BaseUnknownPubKey",
	113: "BaseUnknownPlugin",
	201: "GovUnknownEntity",
	202: "GovUnknownGroup",
	203: "GovUnknownProposal",
	204: "GovDuplicateGroup",
	205: "GovDuplicateMember",
	206: "GovDuplicateProposal",
	207: "GovDuplicateVote",
	208: "GovInvalidMember",
	209: "GovInvalidVote",
	210: "GovInvalidVotingPower",
}
var CodeType_value = map[string]int32{
	"OK":                       0,
	"InternalError":            1,
	"EncodingError":            2,
	"BadNonce":                 3,
	"Unauthorized":             4,
	"InsufficientFunds":        5,
	"UnknownRequest":           6,
	"BaseDuplicateAddress":     101,
	"BaseEncodingError":        102,
	"BaseInsufficientFees":     103,
	"BaseInsufficientFunds":    104,
	"BaseInsufficientGasPrice": 105,
	"BaseInvalidInput":         106,
	"BaseInvalidOutput":        107,
	"BaseInvalidPubKey":        108,
	"BaseInvalidSequence":      109,
	"BaseInvalidSignature":     110,
	"BaseUnknownAddress":       111,
	"BaseUnknownPubKey":        112,
	"BaseUnknownPlugin":        113,
	"GovUnknownEntity":         201,
	"GovUnknownGroup":          202,
	"GovUnknownProposal":       203,
	"GovDuplicateGroup":        204,
	"GovDuplicateMember":       205,
	"GovDuplicateProposal":     206,
	"GovDuplicateVote":         207,
	"GovInvalidMember":         208,
	"GovInvalidVote":           209,
	"GovInvalidVotingPower":    210,
}

func (x CodeType) String() string {
	return proto.EnumName(CodeType_name, int32(x))
}
func (CodeType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type Request struct {
	// Types that are valid to be assigned to Value:
	//	*Request_Echo
	//	*Request_Flush
	//	*Request_Info
	//	*Request_SetOption
	//	*Request_AppendTx
	//	*Request_CheckTx
	//	*Request_Commit
	//	*Request_Query
	//	*Request_InitChain
	//	*Request_BeginBlock
	//	*Request_EndBlock
	//	*Request_Proof
	Value isRequest_Value `protobuf_oneof:"value"`
}

func (m *Request) Reset()                    { *m = Request{} }
func (m *Request) String() string            { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()               {}
func (*Request) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type isRequest_Value interface {
	isRequest_Value()
}

type Request_Echo struct {
	Echo *RequestEcho `protobuf:"bytes,1,opt,name=echo,oneof"`
}
type Request_Flush struct {
	Flush *RequestFlush `protobuf:"bytes,2,opt,name=flush,oneof"`
}
type Request_Info struct {
	Info *RequestInfo `protobuf:"bytes,3,opt,name=info,oneof"`
}
type Request_SetOption struct {
	SetOption *RequestSetOption `protobuf:"bytes,4,opt,name=set_option,json=setOption,oneof"`
}
type Request_AppendTx struct {
	AppendTx *RequestAppendTx `protobuf:"bytes,5,opt,name=append_tx,json=appendTx,oneof"`
}
type Request_CheckTx struct {
	CheckTx *RequestCheckTx `protobuf:"bytes,6,opt,name=check_tx,json=checkTx,oneof"`
}
type Request_Commit struct {
	Commit *RequestCommit `protobuf:"bytes,7,opt,name=commit,oneof"`
}
type Request_Query struct {
	Query *RequestQuery `protobuf:"bytes,8,opt,name=query,oneof"`
}
type Request_InitChain struct {
	InitChain *RequestInitChain `protobuf:"bytes,9,opt,name=init_chain,json=initChain,oneof"`
}
type Request_BeginBlock struct {
	BeginBlock *RequestBeginBlock `protobuf:"bytes,10,opt,name=begin_block,json=beginBlock,oneof"`
}
type Request_EndBlock struct {
	EndBlock *RequestEndBlock `protobuf:"bytes,11,opt,name=end_block,json=endBlock,oneof"`
}
type Request_Proof struct {
	Proof *RequestProof `protobuf:"bytes,12,opt,name=proof,oneof"`
}

func (*Request_Echo) isRequest_Value()       {}
func (*Request_Flush) isRequest_Value()      {}
func (*Request_Info) isRequest_Value()       {}
func (*Request_SetOption) isRequest_Value()  {}
func (*Request_AppendTx) isRequest_Value()   {}
func (*Request_CheckTx) isRequest_Value()    {}
func (*Request_Commit) isRequest_Value()     {}
func (*Request_Query) isRequest_Value()      {}
func (*Request_InitChain) isRequest_Value()  {}
func (*Request_BeginBlock) isRequest_Value() {}
func (*Request_EndBlock) isRequest_Value()   {}
func (*Request_Proof) isRequest_Value()      {}

func (m *Request) GetValue() isRequest_Value {
	if m != nil {
		return m.Value
	}
	return nil
}

func (m *Request) GetEcho() *RequestEcho {
	if x, ok := m.GetValue().(*Request_Echo); ok {
		return x.Echo
	}
	return nil
}

func (m *Request) GetFlush() *RequestFlush {
	if x, ok := m.GetValue().(*Request_Flush); ok {
		return x.Flush
	}
	return nil
}

func (m *Request) GetInfo() *RequestInfo {
	if x, ok := m.GetValue().(*Request_Info); ok {
		return x.Info
	}
	return nil
}

func (m *Request) GetSetOption() *RequestSetOption {
	if x, ok := m.GetValue().(*Request_SetOption); ok {
		return x.SetOption
	}
	return nil
}

func (m *Request) GetAppendTx() *RequestAppendTx {
	if x, ok := m.GetValue().(*Request_AppendTx); ok {
		return x.AppendTx
	}
	return nil
}

func (m *Request) GetCheckTx() *RequestCheckTx {
	if x, ok := m.GetValue().(*Request_CheckTx); ok {
		return x.CheckTx
	}
	return nil
}

func (m *Request) GetCommit() *RequestCommit {
	if x, ok := m.GetValue().(*Request_Commit); ok {
		return x.Commit
	}
	return nil
}

func (m *Request) GetQuery() *RequestQuery {
	if x, ok := m.GetValue().(*Request_Query); ok {
		return x.Query
	}
	return nil
}

func (m *Request) GetInitChain() *RequestInitChain {
	if x, ok := m.GetValue().(*Request_InitChain); ok {
		return x.InitChain
	}
	return nil
}

func (m *Request) GetBeginBlock() *RequestBeginBlock {
	if x, ok := m.GetValue().(*Request_BeginBlock); ok {
		return x.BeginBlock
	}
	return nil
}

func (m *Request) GetEndBlock() *RequestEndBlock {
	if x, ok := m.GetValue().(*Request_EndBlock); ok {
		return x.EndBlock
	}
	return nil
}

func (m *Request) GetProof() *RequestProof {
	if x, ok := m.GetValue().(*Request_Proof); ok {
		return x.Proof
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*Request) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _Request_OneofMarshaler, _Request_OneofUnmarshaler, _Request_OneofSizer, []interface{}{
		(*Request_Echo)(nil),
		(*Request_Flush)(nil),
		(*Request_Info)(nil),
		(*Request_SetOption)(nil),
		(*Request_AppendTx)(nil),
		(*Request_CheckTx)(nil),
		(*Request_Commit)(nil),
		(*Request_Query)(nil),
		(*Request_InitChain)(nil),
		(*Request_BeginBlock)(nil),
		(*Request_EndBlock)(nil),
		(*Request_Proof)(nil),
	}
}

func _Request_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*Request)
	// value
	switch x := m.Value.(type) {
	case *Request_Echo:
		b.EncodeVarint(1<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Echo); err != nil {
			return err
		}
	case *Request_Flush:
		b.EncodeVarint(2<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Flush); err != nil {
			return err
		}
	case *Request_Info:
		b.EncodeVarint(3<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Info); err != nil {
			return err
		}
	case *Request_SetOption:
		b.EncodeVarint(4<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.SetOption); err != nil {
			return err
		}
	case *Request_AppendTx:
		b.EncodeVarint(5<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.AppendTx); err != nil {
			return err
		}
	case *Request_CheckTx:
		b.EncodeVarint(6<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.CheckTx); err != nil {
			return err
		}
	case *Request_Commit:
		b.EncodeVarint(7<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Commit); err != nil {
			return err
		}
	case *Request_Query:
		b.EncodeVarint(8<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Query); err != nil {
			return err
		}
	case *Request_InitChain:
		b.EncodeVarint(9<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.InitChain); err != nil {
			return err
		}
	case *Request_BeginBlock:
		b.EncodeVarint(10<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.BeginBlock); err != nil {
			return err
		}
	case *Request_EndBlock:
		b.EncodeVarint(11<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.EndBlock); err != nil {
			return err
		}
	case *Request_Proof:
		b.EncodeVarint(12<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Proof); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("Request.Value has unexpected type %T", x)
	}
	return nil
}

func _Request_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*Request)
	switch tag {
	case 1: // value.echo
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(RequestEcho)
		err := b.DecodeMessage(msg)
		m.Value = &Request_Echo{msg}
		return true, err
	case 2: // value.flush
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(RequestFlush)
		err := b.DecodeMessage(msg)
		m.Value = &Request_Flush{msg}
		return true, err
	case 3: // value.info
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(RequestInfo)
		err := b.DecodeMessage(msg)
		m.Value = &Request_Info{msg}
		return true, err
	case 4: // value.set_option
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(RequestSetOption)
		err := b.DecodeMessage(msg)
		m.Value = &Request_SetOption{msg}
		return true, err
	case 5: // value.append_tx
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(RequestAppendTx)
		err := b.DecodeMessage(msg)
		m.Value = &Request_AppendTx{msg}
		return true, err
	case 6: // value.check_tx
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(RequestCheckTx)
		err := b.DecodeMessage(msg)
		m.Value = &Request_CheckTx{msg}
		return true, err
	case 7: // value.commit
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(RequestCommit)
		err := b.DecodeMessage(msg)
		m.Value = &Request_Commit{msg}
		return true, err
	case 8: // value.query
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(RequestQuery)
		err := b.DecodeMessage(msg)
		m.Value = &Request_Query{msg}
		return true, err
	case 9: // value.init_chain
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(RequestInitChain)
		err := b.DecodeMessage(msg)
		m.Value = &Request_InitChain{msg}
		return true, err
	case 10: // value.begin_block
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(RequestBeginBlock)
		err := b.DecodeMessage(msg)
		m.Value = &Request_BeginBlock{msg}
		return true, err
	case 11: // value.end_block
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(RequestEndBlock)
		err := b.DecodeMessage(msg)
		m.Value = &Request_EndBlock{msg}
		return true, err
	case 12: // value.proof
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(RequestProof)
		err := b.DecodeMessage(msg)
		m.Value = &Request_Proof{msg}
		return true, err
	default:
		return false, nil
	}
}

func _Request_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*Request)
	// value
	switch x := m.Value.(type) {
	case *Request_Echo:
		s := proto.Size(x.Echo)
		n += proto.SizeVarint(1<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Request_Flush:
		s := proto.Size(x.Flush)
		n += proto.SizeVarint(2<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Request_Info:
		s := proto.Size(x.Info)
		n += proto.SizeVarint(3<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Request_SetOption:
		s := proto.Size(x.SetOption)
		n += proto.SizeVarint(4<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Request_AppendTx:
		s := proto.Size(x.AppendTx)
		n += proto.SizeVarint(5<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Request_CheckTx:
		s := proto.Size(x.CheckTx)
		n += proto.SizeVarint(6<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Request_Commit:
		s := proto.Size(x.Commit)
		n += proto.SizeVarint(7<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Request_Query:
		s := proto.Size(x.Query)
		n += proto.SizeVarint(8<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Request_InitChain:
		s := proto.Size(x.InitChain)
		n += proto.SizeVarint(9<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Request_BeginBlock:
		s := proto.Size(x.BeginBlock)
		n += proto.SizeVarint(10<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Request_EndBlock:
		s := proto.Size(x.EndBlock)
		n += proto.SizeVarint(11<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Request_Proof:
		s := proto.Size(x.Proof)
		n += proto.SizeVarint(12<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type RequestEcho struct {
	Message string `protobuf:"bytes,1,opt,name=message" json:"message,omitempty"`
}

func (m *RequestEcho) Reset()                    { *m = RequestEcho{} }
func (m *RequestEcho) String() string            { return proto.CompactTextString(m) }
func (*RequestEcho) ProtoMessage()               {}
func (*RequestEcho) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *RequestEcho) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type RequestFlush struct {
}

func (m *RequestFlush) Reset()                    { *m = RequestFlush{} }
func (m *RequestFlush) String() string            { return proto.CompactTextString(m) }
func (*RequestFlush) ProtoMessage()               {}
func (*RequestFlush) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

type RequestInfo struct {
}

func (m *RequestInfo) Reset()                    { *m = RequestInfo{} }
func (m *RequestInfo) String() string            { return proto.CompactTextString(m) }
func (*RequestInfo) ProtoMessage()               {}
func (*RequestInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

type RequestSetOption struct {
	Key   string `protobuf:"bytes,1,opt,name=key" json:"key,omitempty"`
	Value string `protobuf:"bytes,2,opt,name=value" json:"value,omitempty"`
}

func (m *RequestSetOption) Reset()                    { *m = RequestSetOption{} }
func (m *RequestSetOption) String() string            { return proto.CompactTextString(m) }
func (*RequestSetOption) ProtoMessage()               {}
func (*RequestSetOption) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *RequestSetOption) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *RequestSetOption) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type RequestAppendTx struct {
	Tx []byte `protobuf:"bytes,1,opt,name=tx,proto3" json:"tx,omitempty"`
}

func (m *RequestAppendTx) Reset()                    { *m = RequestAppendTx{} }
func (m *RequestAppendTx) String() string            { return proto.CompactTextString(m) }
func (*RequestAppendTx) ProtoMessage()               {}
func (*RequestAppendTx) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *RequestAppendTx) GetTx() []byte {
	if m != nil {
		return m.Tx
	}
	return nil
}

type RequestCheckTx struct {
	Tx []byte `protobuf:"bytes,1,opt,name=tx,proto3" json:"tx,omitempty"`
}

func (m *RequestCheckTx) Reset()                    { *m = RequestCheckTx{} }
func (m *RequestCheckTx) String() string            { return proto.CompactTextString(m) }
func (*RequestCheckTx) ProtoMessage()               {}
func (*RequestCheckTx) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *RequestCheckTx) GetTx() []byte {
	if m != nil {
		return m.Tx
	}
	return nil
}

type RequestQuery struct {
	Query []byte `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
}

func (m *RequestQuery) Reset()                    { *m = RequestQuery{} }
func (m *RequestQuery) String() string            { return proto.CompactTextString(m) }
func (*RequestQuery) ProtoMessage()               {}
func (*RequestQuery) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *RequestQuery) GetQuery() []byte {
	if m != nil {
		return m.Query
	}
	return nil
}

type RequestProof struct {
	Key    []byte `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Height int64  `protobuf:"varint,2,opt,name=height" json:"height,omitempty"`
}

func (m *RequestProof) Reset()                    { *m = RequestProof{} }
func (m *RequestProof) String() string            { return proto.CompactTextString(m) }
func (*RequestProof) ProtoMessage()               {}
func (*RequestProof) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *RequestProof) GetKey() []byte {
	if m != nil {
		return m.Key
	}
	return nil
}

func (m *RequestProof) GetHeight() int64 {
	if m != nil {
		return m.Height
	}
	return 0
}

type RequestCommit struct {
}

func (m *RequestCommit) Reset()                    { *m = RequestCommit{} }
func (m *RequestCommit) String() string            { return proto.CompactTextString(m) }
func (*RequestCommit) ProtoMessage()               {}
func (*RequestCommit) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

type RequestInitChain struct {
	Validators []*Validator `protobuf:"bytes,1,rep,name=validators" json:"validators,omitempty"`
}

func (m *RequestInitChain) Reset()                    { *m = RequestInitChain{} }
func (m *RequestInitChain) String() string            { return proto.CompactTextString(m) }
func (*RequestInitChain) ProtoMessage()               {}
func (*RequestInitChain) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

func (m *RequestInitChain) GetValidators() []*Validator {
	if m != nil {
		return m.Validators
	}
	return nil
}

type RequestBeginBlock struct {
	Hash   []byte  `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	Header *Header `protobuf:"bytes,2,opt,name=header" json:"header,omitempty"`
}

func (m *RequestBeginBlock) Reset()                    { *m = RequestBeginBlock{} }
func (m *RequestBeginBlock) String() string            { return proto.CompactTextString(m) }
func (*RequestBeginBlock) ProtoMessage()               {}
func (*RequestBeginBlock) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{11} }

func (m *RequestBeginBlock) GetHash() []byte {
	if m != nil {
		return m.Hash
	}
	return nil
}

func (m *RequestBeginBlock) GetHeader() *Header {
	if m != nil {
		return m.Header
	}
	return nil
}

type RequestEndBlock struct {
	Height uint64 `protobuf:"varint,1,opt,name=height" json:"height,omitempty"`
}

func (m *RequestEndBlock) Reset()                    { *m = RequestEndBlock{} }
func (m *RequestEndBlock) String() string            { return proto.CompactTextString(m) }
func (*RequestEndBlock) ProtoMessage()               {}
func (*RequestEndBlock) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{12} }

func (m *RequestEndBlock) GetHeight() uint64 {
	if m != nil {
		return m.Height
	}
	return 0
}

type Response struct {
	// Types that are valid to be assigned to Value:
	//	*Response_Exception
	//	*Response_Echo
	//	*Response_Flush
	//	*Response_Info
	//	*Response_SetOption
	//	*Response_AppendTx
	//	*Response_CheckTx
	//	*Response_Commit
	//	*Response_Query
	//	*Response_InitChain
	//	*Response_BeginBlock
	//	*Response_EndBlock
	//	*Response_Proof
	Value isResponse_Value `protobuf_oneof:"value"`
}

func (m *Response) Reset()                    { *m = Response{} }
func (m *Response) String() string            { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()               {}
func (*Response) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{13} }

type isResponse_Value interface {
	isResponse_Value()
}

type Response_Exception struct {
	Exception *ResponseException `protobuf:"bytes,1,opt,name=exception,oneof"`
}
type Response_Echo struct {
	Echo *ResponseEcho `protobuf:"bytes,2,opt,name=echo,oneof"`
}
type Response_Flush struct {
	Flush *ResponseFlush `protobuf:"bytes,3,opt,name=flush,oneof"`
}
type Response_Info struct {
	Info *ResponseInfo `protobuf:"bytes,4,opt,name=info,oneof"`
}
type Response_SetOption struct {
	SetOption *ResponseSetOption `protobuf:"bytes,5,opt,name=set_option,json=setOption,oneof"`
}
type Response_AppendTx struct {
	AppendTx *ResponseAppendTx `protobuf:"bytes,6,opt,name=append_tx,json=appendTx,oneof"`
}
type Response_CheckTx struct {
	CheckTx *ResponseCheckTx `protobuf:"bytes,7,opt,name=check_tx,json=checkTx,oneof"`
}
type Response_Commit struct {
	Commit *ResponseCommit `protobuf:"bytes,8,opt,name=commit,oneof"`
}
type Response_Query struct {
	Query *ResponseQuery `protobuf:"bytes,9,opt,name=query,oneof"`
}
type Response_InitChain struct {
	InitChain *ResponseInitChain `protobuf:"bytes,10,opt,name=init_chain,json=initChain,oneof"`
}
type Response_BeginBlock struct {
	BeginBlock *ResponseBeginBlock `protobuf:"bytes,11,opt,name=begin_block,json=beginBlock,oneof"`
}
type Response_EndBlock struct {
	EndBlock *ResponseEndBlock `protobuf:"bytes,12,opt,name=end_block,json=endBlock,oneof"`
}
type Response_Proof struct {
	Proof *ResponseProof `protobuf:"bytes,13,opt,name=proof,oneof"`
}

func (*Response_Exception) isResponse_Value()  {}
func (*Response_Echo) isResponse_Value()       {}
func (*Response_Flush) isResponse_Value()      {}
func (*Response_Info) isResponse_Value()       {}
func (*Response_SetOption) isResponse_Value()  {}
func (*Response_AppendTx) isResponse_Value()   {}
func (*Response_CheckTx) isResponse_Value()    {}
func (*Response_Commit) isResponse_Value()     {}
func (*Response_Query) isResponse_Value()      {}
func (*Response_InitChain) isResponse_Value()  {}
func (*Response_BeginBlock) isResponse_Value() {}
func (*Response_EndBlock) isResponse_Value()   {}
func (*Response_Proof) isResponse_Value()      {}

func (m *Response) GetValue() isResponse_Value {
	if m != nil {
		return m.Value
	}
	return nil
}

func (m *Response) GetException() *ResponseException {
	if x, ok := m.GetValue().(*Response_Exception); ok {
		return x.Exception
	}
	return nil
}

func (m *Response) GetEcho() *ResponseEcho {
	if x, ok := m.GetValue().(*Response_Echo); ok {
		return x.Echo
	}
	return nil
}

func (m *Response) GetFlush() *ResponseFlush {
	if x, ok := m.GetValue().(*Response_Flush); ok {
		return x.Flush
	}
	return nil
}

func (m *Response) GetInfo() *ResponseInfo {
	if x, ok := m.GetValue().(*Response_Info); ok {
		return x.Info
	}
	return nil
}

func (m *Response) GetSetOption() *ResponseSetOption {
	if x, ok := m.GetValue().(*Response_SetOption); ok {
		return x.SetOption
	}
	return nil
}

func (m *Response) GetAppendTx() *ResponseAppendTx {
	if x, ok := m.GetValue().(*Response_AppendTx); ok {
		return x.AppendTx
	}
	return nil
}

func (m *Response) GetCheckTx() *ResponseCheckTx {
	if x, ok := m.GetValue().(*Response_CheckTx); ok {
		return x.CheckTx
	}
	return nil
}

func (m *Response) GetCommit() *ResponseCommit {
	if x, ok := m.GetValue().(*Response_Commit); ok {
		return x.Commit
	}
	return nil
}

func (m *Response) GetQuery() *ResponseQuery {
	if x, ok := m.GetValue().(*Response_Query); ok {
		return x.Query
	}
	return nil
}

func (m *Response) GetInitChain() *ResponseInitChain {
	if x, ok := m.GetValue().(*Response_InitChain); ok {
		return x.InitChain
	}
	return nil
}

func (m *Response) GetBeginBlock() *ResponseBeginBlock {
	if x, ok := m.GetValue().(*Response_BeginBlock); ok {
		return x.BeginBlock
	}
	return nil
}

func (m *Response) GetEndBlock() *ResponseEndBlock {
	if x, ok := m.GetValue().(*Response_EndBlock); ok {
		return x.EndBlock
	}
	return nil
}

func (m *Response) GetProof() *ResponseProof {
	if x, ok := m.GetValue().(*Response_Proof); ok {
		return x.Proof
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*Response) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _Response_OneofMarshaler, _Response_OneofUnmarshaler, _Response_OneofSizer, []interface{}{
		(*Response_Exception)(nil),
		(*Response_Echo)(nil),
		(*Response_Flush)(nil),
		(*Response_Info)(nil),
		(*Response_SetOption)(nil),
		(*Response_AppendTx)(nil),
		(*Response_CheckTx)(nil),
		(*Response_Commit)(nil),
		(*Response_Query)(nil),
		(*Response_InitChain)(nil),
		(*Response_BeginBlock)(nil),
		(*Response_EndBlock)(nil),
		(*Response_Proof)(nil),
	}
}

func _Response_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*Response)
	// value
	switch x := m.Value.(type) {
	case *Response_Exception:
		b.EncodeVarint(1<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Exception); err != nil {
			return err
		}
	case *Response_Echo:
		b.EncodeVarint(2<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Echo); err != nil {
			return err
		}
	case *Response_Flush:
		b.EncodeVarint(3<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Flush); err != nil {
			return err
		}
	case *Response_Info:
		b.EncodeVarint(4<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Info); err != nil {
			return err
		}
	case *Response_SetOption:
		b.EncodeVarint(5<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.SetOption); err != nil {
			return err
		}
	case *Response_AppendTx:
		b.EncodeVarint(6<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.AppendTx); err != nil {
			return err
		}
	case *Response_CheckTx:
		b.EncodeVarint(7<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.CheckTx); err != nil {
			return err
		}
	case *Response_Commit:
		b.EncodeVarint(8<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Commit); err != nil {
			return err
		}
	case *Response_Query:
		b.EncodeVarint(9<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Query); err != nil {
			return err
		}
	case *Response_InitChain:
		b.EncodeVarint(10<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.InitChain); err != nil {
			return err
		}
	case *Response_BeginBlock:
		b.EncodeVarint(11<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.BeginBlock); err != nil {
			return err
		}
	case *Response_EndBlock:
		b.EncodeVarint(12<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.EndBlock); err != nil {
			return err
		}
	case *Response_Proof:
		b.EncodeVarint(13<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Proof); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("Response.Value has unexpected type %T", x)
	}
	return nil
}

func _Response_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*Response)
	switch tag {
	case 1: // value.exception
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(ResponseException)
		err := b.DecodeMessage(msg)
		m.Value = &Response_Exception{msg}
		return true, err
	case 2: // value.echo
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(ResponseEcho)
		err := b.DecodeMessage(msg)
		m.Value = &Response_Echo{msg}
		return true, err
	case 3: // value.flush
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(ResponseFlush)
		err := b.DecodeMessage(msg)
		m.Value = &Response_Flush{msg}
		return true, err
	case 4: // value.info
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(ResponseInfo)
		err := b.DecodeMessage(msg)
		m.Value = &Response_Info{msg}
		return true, err
	case 5: // value.set_option
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(ResponseSetOption)
		err := b.DecodeMessage(msg)
		m.Value = &Response_SetOption{msg}
		return true, err
	case 6: // value.append_tx
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(ResponseAppendTx)
		err := b.DecodeMessage(msg)
		m.Value = &Response_AppendTx{msg}
		return true, err
	case 7: // value.check_tx
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(ResponseCheckTx)
		err := b.DecodeMessage(msg)
		m.Value = &Response_CheckTx{msg}
		return true, err
	case 8: // value.commit
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(ResponseCommit)
		err := b.DecodeMessage(msg)
		m.Value = &Response_Commit{msg}
		return true, err
	case 9: // value.query
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(ResponseQuery)
		err := b.DecodeMessage(msg)
		m.Value = &Response_Query{msg}
		return true, err
	case 10: // value.init_chain
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(ResponseInitChain)
		err := b.DecodeMessage(msg)
		m.Value = &Response_InitChain{msg}
		return true, err
	case 11: // value.begin_block
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(ResponseBeginBlock)
		err := b.DecodeMessage(msg)
		m.Value = &Response_BeginBlock{msg}
		return true, err
	case 12: // value.end_block
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(ResponseEndBlock)
		err := b.DecodeMessage(msg)
		m.Value = &Response_EndBlock{msg}
		return true, err
	case 13: // value.proof
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(ResponseProof)
		err := b.DecodeMessage(msg)
		m.Value = &Response_Proof{msg}
		return true, err
	default:
		return false, nil
	}
}

func _Response_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*Response)
	// value
	switch x := m.Value.(type) {
	case *Response_Exception:
		s := proto.Size(x.Exception)
		n += proto.SizeVarint(1<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Response_Echo:
		s := proto.Size(x.Echo)
		n += proto.SizeVarint(2<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Response_Flush:
		s := proto.Size(x.Flush)
		n += proto.SizeVarint(3<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Response_Info:
		s := proto.Size(x.Info)
		n += proto.SizeVarint(4<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Response_SetOption:
		s := proto.Size(x.SetOption)
		n += proto.SizeVarint(5<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Response_AppendTx:
		s := proto.Size(x.AppendTx)
		n += proto.SizeVarint(6<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Response_CheckTx:
		s := proto.Size(x.CheckTx)
		n += proto.SizeVarint(7<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Response_Commit:
		s := proto.Size(x.Commit)
		n += proto.SizeVarint(8<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Response_Query:
		s := proto.Size(x.Query)
		n += proto.SizeVarint(9<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Response_InitChain:
		s := proto.Size(x.InitChain)
		n += proto.SizeVarint(10<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Response_BeginBlock:
		s := proto.Size(x.BeginBlock)
		n += proto.SizeVarint(11<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Response_EndBlock:
		s := proto.Size(x.EndBlock)
		n += proto.SizeVarint(12<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Response_Proof:
		s := proto.Size(x.Proof)
		n += proto.SizeVarint(13<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type ResponseException struct {
	Error string `protobuf:"bytes,1,opt,name=error" json:"error,omitempty"`
}

func (m *ResponseException) Reset()                    { *m = ResponseException{} }
func (m *ResponseException) String() string            { return proto.CompactTextString(m) }
func (*ResponseException) ProtoMessage()               {}
func (*ResponseException) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{14} }

func (m *ResponseException) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

type ResponseEcho struct {
	Message string `protobuf:"bytes,1,opt,name=message" json:"message,omitempty"`
}

func (m *ResponseEcho) Reset()                    { *m = ResponseEcho{} }
func (m *ResponseEcho) String() string            { return proto.CompactTextString(m) }
func (*ResponseEcho) ProtoMessage()               {}
func (*ResponseEcho) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{15} }

func (m *ResponseEcho) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type ResponseFlush struct {
}

func (m *ResponseFlush) Reset()                    { *m = ResponseFlush{} }
func (m *ResponseFlush) String() string            { return proto.CompactTextString(m) }
func (*ResponseFlush) ProtoMessage()               {}
func (*ResponseFlush) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{16} }

type ResponseInfo struct {
	Info      string         `protobuf:"bytes,1,opt,name=info" json:"info,omitempty"`
	TmspInfo  *TMSPInfo      `protobuf:"bytes,2,opt,name=tmsp_info,json=tmspInfo" json:"tmsp_info,omitempty"`
	LastBlock *LastBlockInfo `protobuf:"bytes,3,opt,name=last_block,json=lastBlock" json:"last_block,omitempty"`
	Config    *ConfigInfo    `protobuf:"bytes,4,opt,name=config" json:"config,omitempty"`
}

func (m *ResponseInfo) Reset()                    { *m = ResponseInfo{} }
func (m *ResponseInfo) String() string            { return proto.CompactTextString(m) }
func (*ResponseInfo) ProtoMessage()               {}
func (*ResponseInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{17} }

func (m *ResponseInfo) GetInfo() string {
	if m != nil {
		return m.Info
	}
	return ""
}

func (m *ResponseInfo) GetTmspInfo() *TMSPInfo {
	if m != nil {
		return m.TmspInfo
	}
	return nil
}

func (m *ResponseInfo) GetLastBlock() *LastBlockInfo {
	if m != nil {
		return m.LastBlock
	}
	return nil
}

func (m *ResponseInfo) GetConfig() *ConfigInfo {
	if m != nil {
		return m.Config
	}
	return nil
}

type ResponseSetOption struct {
	Log string `protobuf:"bytes,1,opt,name=log" json:"log,omitempty"`
}

func (m *ResponseSetOption) Reset()                    { *m = ResponseSetOption{} }
func (m *ResponseSetOption) String() string            { return proto.CompactTextString(m) }
func (*ResponseSetOption) ProtoMessage()               {}
func (*ResponseSetOption) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{18} }

func (m *ResponseSetOption) GetLog() string {
	if m != nil {
		return m.Log
	}
	return ""
}

type ResponseAppendTx struct {
	Code CodeType `protobuf:"varint,1,opt,name=code,enum=types.CodeType" json:"code,omitempty"`
	Data []byte   `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	Log  string   `protobuf:"bytes,3,opt,name=log" json:"log,omitempty"`
}

func (m *ResponseAppendTx) Reset()                    { *m = ResponseAppendTx{} }
func (m *ResponseAppendTx) String() string            { return proto.CompactTextString(m) }
func (*ResponseAppendTx) ProtoMessage()               {}
func (*ResponseAppendTx) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{19} }

func (m *ResponseAppendTx) GetCode() CodeType {
	if m != nil {
		return m.Code
	}
	return CodeType_OK
}

func (m *ResponseAppendTx) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *ResponseAppendTx) GetLog() string {
	if m != nil {
		return m.Log
	}
	return ""
}

type ResponseCheckTx struct {
	Code CodeType `protobuf:"varint,1,opt,name=code,enum=types.CodeType" json:"code,omitempty"`
	Data []byte   `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	Log  string   `protobuf:"bytes,3,opt,name=log" json:"log,omitempty"`
}

func (m *ResponseCheckTx) Reset()                    { *m = ResponseCheckTx{} }
func (m *ResponseCheckTx) String() string            { return proto.CompactTextString(m) }
func (*ResponseCheckTx) ProtoMessage()               {}
func (*ResponseCheckTx) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{20} }

func (m *ResponseCheckTx) GetCode() CodeType {
	if m != nil {
		return m.Code
	}
	return CodeType_OK
}

func (m *ResponseCheckTx) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *ResponseCheckTx) GetLog() string {
	if m != nil {
		return m.Log
	}
	return ""
}

type ResponseQuery struct {
	Code CodeType `protobuf:"varint,1,opt,name=code,enum=types.CodeType" json:"code,omitempty"`
	Data []byte   `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	Log  string   `protobuf:"bytes,3,opt,name=log" json:"log,omitempty"`
}

func (m *ResponseQuery) Reset()                    { *m = ResponseQuery{} }
func (m *ResponseQuery) String() string            { return proto.CompactTextString(m) }
func (*ResponseQuery) ProtoMessage()               {}
func (*ResponseQuery) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{21} }

func (m *ResponseQuery) GetCode() CodeType {
	if m != nil {
		return m.Code
	}
	return CodeType_OK
}

func (m *ResponseQuery) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *ResponseQuery) GetLog() string {
	if m != nil {
		return m.Log
	}
	return ""
}

type ResponseProof struct {
	Code CodeType `protobuf:"varint,1,opt,name=code,enum=types.CodeType" json:"code,omitempty"`
	Data []byte   `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	Log  string   `protobuf:"bytes,3,opt,name=log" json:"log,omitempty"`
}

func (m *ResponseProof) Reset()                    { *m = ResponseProof{} }
func (m *ResponseProof) String() string            { return proto.CompactTextString(m) }
func (*ResponseProof) ProtoMessage()               {}
func (*ResponseProof) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{22} }

func (m *ResponseProof) GetCode() CodeType {
	if m != nil {
		return m.Code
	}
	return CodeType_OK
}

func (m *ResponseProof) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *ResponseProof) GetLog() string {
	if m != nil {
		return m.Log
	}
	return ""
}

type ResponseCommit struct {
	Code CodeType `protobuf:"varint,1,opt,name=code,enum=types.CodeType" json:"code,omitempty"`
	Data []byte   `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	Log  string   `protobuf:"bytes,3,opt,name=log" json:"log,omitempty"`
}

func (m *ResponseCommit) Reset()                    { *m = ResponseCommit{} }
func (m *ResponseCommit) String() string            { return proto.CompactTextString(m) }
func (*ResponseCommit) ProtoMessage()               {}
func (*ResponseCommit) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{23} }

func (m *ResponseCommit) GetCode() CodeType {
	if m != nil {
		return m.Code
	}
	return CodeType_OK
}

func (m *ResponseCommit) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *ResponseCommit) GetLog() string {
	if m != nil {
		return m.Log
	}
	return ""
}

type ResponseInitChain struct {
}

func (m *ResponseInitChain) Reset()                    { *m = ResponseInitChain{} }
func (m *ResponseInitChain) String() string            { return proto.CompactTextString(m) }
func (*ResponseInitChain) ProtoMessage()               {}
func (*ResponseInitChain) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{24} }

type ResponseBeginBlock struct {
}

func (m *ResponseBeginBlock) Reset()                    { *m = ResponseBeginBlock{} }
func (m *ResponseBeginBlock) String() string            { return proto.CompactTextString(m) }
func (*ResponseBeginBlock) ProtoMessage()               {}
func (*ResponseBeginBlock) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{25} }

type ResponseEndBlock struct {
	Diffs []*Validator `protobuf:"bytes,4,rep,name=diffs" json:"diffs,omitempty"`
}

func (m *ResponseEndBlock) Reset()                    { *m = ResponseEndBlock{} }
func (m *ResponseEndBlock) String() string            { return proto.CompactTextString(m) }
func (*ResponseEndBlock) ProtoMessage()               {}
func (*ResponseEndBlock) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{26} }

func (m *ResponseEndBlock) GetDiffs() []*Validator {
	if m != nil {
		return m.Diffs
	}
	return nil
}

type TMSPInfo struct {
	Version string `protobuf:"bytes,1,opt,name=Version" json:"Version,omitempty"`
}

func (m *TMSPInfo) Reset()                    { *m = TMSPInfo{} }
func (m *TMSPInfo) String() string            { return proto.CompactTextString(m) }
func (*TMSPInfo) ProtoMessage()               {}
func (*TMSPInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{27} }

func (m *TMSPInfo) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

type LastBlockInfo struct {
	BlockHeight uint64 `protobuf:"varint,1,opt,name=block_height,json=blockHeight" json:"block_height,omitempty"`
	AppHash     []byte `protobuf:"bytes,2,opt,name=app_hash,json=appHash,proto3" json:"app_hash,omitempty"`
}

func (m *LastBlockInfo) Reset()                    { *m = LastBlockInfo{} }
func (m *LastBlockInfo) String() string            { return proto.CompactTextString(m) }
func (*LastBlockInfo) ProtoMessage()               {}
func (*LastBlockInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{28} }

func (m *LastBlockInfo) GetBlockHeight() uint64 {
	if m != nil {
		return m.BlockHeight
	}
	return 0
}

func (m *LastBlockInfo) GetAppHash() []byte {
	if m != nil {
		return m.AppHash
	}
	return nil
}

type ConfigInfo struct {
	MaxBlockSizeBytes uint64 `protobuf:"varint,1,opt,name=max_block_size_bytes,json=maxBlockSizeBytes" json:"max_block_size_bytes,omitempty"`
	MaxBlockSizeTxs   uint64 `protobuf:"varint,2,opt,name=max_block_size_txs,json=maxBlockSizeTxs" json:"max_block_size_txs,omitempty"`
	MaxTxSize         uint64 `protobuf:"varint,3,opt,name=max_tx_size,json=maxTxSize" json:"max_tx_size,omitempty"`
}

func (m *ConfigInfo) Reset()                    { *m = ConfigInfo{} }
func (m *ConfigInfo) String() string            { return proto.CompactTextString(m) }
func (*ConfigInfo) ProtoMessage()               {}
func (*ConfigInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{29} }

func (m *ConfigInfo) GetMaxBlockSizeBytes() uint64 {
	if m != nil {
		return m.MaxBlockSizeBytes
	}
	return 0
}

func (m *ConfigInfo) GetMaxBlockSizeTxs() uint64 {
	if m != nil {
		return m.MaxBlockSizeTxs
	}
	return 0
}

func (m *ConfigInfo) GetMaxTxSize() uint64 {
	if m != nil {
		return m.MaxTxSize
	}
	return 0
}

type Header struct {
	ChainId        string   `protobuf:"bytes,1,opt,name=chain_id,json=chainId" json:"chain_id,omitempty"`
	Height         uint64   `protobuf:"varint,2,opt,name=height" json:"height,omitempty"`
	Time           uint64   `protobuf:"varint,3,opt,name=time" json:"time,omitempty"`
	NumTxs         uint64   `protobuf:"varint,4,opt,name=num_txs,json=numTxs" json:"num_txs,omitempty"`
	LastBlockId    *BlockID `protobuf:"bytes,5,opt,name=last_block_id,json=lastBlockId" json:"last_block_id,omitempty"`
	LastCommitHash []byte   `protobuf:"bytes,6,opt,name=last_commit_hash,json=lastCommitHash,proto3" json:"last_commit_hash,omitempty"`
	DataHash       []byte   `protobuf:"bytes,7,opt,name=data_hash,json=dataHash,proto3" json:"data_hash,omitempty"`
	ValidatorsHash []byte   `protobuf:"bytes,8,opt,name=validators_hash,json=validatorsHash,proto3" json:"validators_hash,omitempty"`
	AppHash        []byte   `protobuf:"bytes,9,opt,name=app_hash,json=appHash,proto3" json:"app_hash,omitempty"`
}

func (m *Header) Reset()                    { *m = Header{} }
func (m *Header) String() string            { return proto.CompactTextString(m) }
func (*Header) ProtoMessage()               {}
func (*Header) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{30} }

func (m *Header) GetChainId() string {
	if m != nil {
		return m.ChainId
	}
	return ""
}

func (m *Header) GetHeight() uint64 {
	if m != nil {
		return m.Height
	}
	return 0
}

func (m *Header) GetTime() uint64 {
	if m != nil {
		return m.Time
	}
	return 0
}

func (m *Header) GetNumTxs() uint64 {
	if m != nil {
		return m.NumTxs
	}
	return 0
}

func (m *Header) GetLastBlockId() *BlockID {
	if m != nil {
		return m.LastBlockId
	}
	return nil
}

func (m *Header) GetLastCommitHash() []byte {
	if m != nil {
		return m.LastCommitHash
	}
	return nil
}

func (m *Header) GetDataHash() []byte {
	if m != nil {
		return m.DataHash
	}
	return nil
}

func (m *Header) GetValidatorsHash() []byte {
	if m != nil {
		return m.ValidatorsHash
	}
	return nil
}

func (m *Header) GetAppHash() []byte {
	if m != nil {
		return m.AppHash
	}
	return nil
}

type BlockID struct {
	Hash  []byte         `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	Parts *PartSetHeader `protobuf:"bytes,2,opt,name=parts" json:"parts,omitempty"`
}

func (m *BlockID) Reset()                    { *m = BlockID{} }
func (m *BlockID) String() string            { return proto.CompactTextString(m) }
func (*BlockID) ProtoMessage()               {}
func (*BlockID) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{31} }

func (m *BlockID) GetHash() []byte {
	if m != nil {
		return m.Hash
	}
	return nil
}

func (m *BlockID) GetParts() *PartSetHeader {
	if m != nil {
		return m.Parts
	}
	return nil
}

type PartSetHeader struct {
	Total uint64 `protobuf:"varint,1,opt,name=total" json:"total,omitempty"`
	Hash  []byte `protobuf:"bytes,2,opt,name=hash,proto3" json:"hash,omitempty"`
}

func (m *PartSetHeader) Reset()                    { *m = PartSetHeader{} }
func (m *PartSetHeader) String() string            { return proto.CompactTextString(m) }
func (*PartSetHeader) ProtoMessage()               {}
func (*PartSetHeader) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{32} }

func (m *PartSetHeader) GetTotal() uint64 {
	if m != nil {
		return m.Total
	}
	return 0
}

func (m *PartSetHeader) GetHash() []byte {
	if m != nil {
		return m.Hash
	}
	return nil
}

type Validator struct {
	PubKey []byte `protobuf:"bytes,1,opt,name=pubKey,proto3" json:"pubKey,omitempty"`
	Power  uint64 `protobuf:"varint,2,opt,name=power" json:"power,omitempty"`
}

func (m *Validator) Reset()                    { *m = Validator{} }
func (m *Validator) String() string            { return proto.CompactTextString(m) }
func (*Validator) ProtoMessage()               {}
func (*Validator) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{33} }

func (m *Validator) GetPubKey() []byte {
	if m != nil {
		return m.PubKey
	}
	return nil
}

func (m *Validator) GetPower() uint64 {
	if m != nil {
		return m.Power
	}
	return 0
}

func init() {
	proto.RegisterType((*Request)(nil), "types.Request")
	proto.RegisterType((*RequestEcho)(nil), "types.RequestEcho")
	proto.RegisterType((*RequestFlush)(nil), "types.RequestFlush")
	proto.RegisterType((*RequestInfo)(nil), "types.RequestInfo")
	proto.RegisterType((*RequestSetOption)(nil), "types.RequestSetOption")
	proto.RegisterType((*RequestAppendTx)(nil), "types.RequestAppendTx")
	proto.RegisterType((*RequestCheckTx)(nil), "types.RequestCheckTx")
	proto.RegisterType((*RequestQuery)(nil), "types.RequestQuery")
	proto.RegisterType((*RequestProof)(nil), "types.RequestProof")
	proto.RegisterType((*RequestCommit)(nil), "types.RequestCommit")
	proto.RegisterType((*RequestInitChain)(nil), "types.RequestInitChain")
	proto.RegisterType((*RequestBeginBlock)(nil), "types.RequestBeginBlock")
	proto.RegisterType((*RequestEndBlock)(nil), "types.RequestEndBlock")
	proto.RegisterType((*Response)(nil), "types.Response")
	proto.RegisterType((*ResponseException)(nil), "types.ResponseException")
	proto.RegisterType((*ResponseEcho)(nil), "types.ResponseEcho")
	proto.RegisterType((*ResponseFlush)(nil), "types.ResponseFlush")
	proto.RegisterType((*ResponseInfo)(nil), "types.ResponseInfo")
	proto.RegisterType((*ResponseSetOption)(nil), "types.ResponseSetOption")
	proto.RegisterType((*ResponseAppendTx)(nil), "types.ResponseAppendTx")
	proto.RegisterType((*ResponseCheckTx)(nil), "types.ResponseCheckTx")
	proto.RegisterType((*ResponseQuery)(nil), "types.ResponseQuery")
	proto.RegisterType((*ResponseProof)(nil), "types.ResponseProof")
	proto.RegisterType((*ResponseCommit)(nil), "types.ResponseCommit")
	proto.RegisterType((*ResponseInitChain)(nil), "types.ResponseInitChain")
	proto.RegisterType((*ResponseBeginBlock)(nil), "types.ResponseBeginBlock")
	proto.RegisterType((*ResponseEndBlock)(nil), "types.ResponseEndBlock")
	proto.RegisterType((*TMSPInfo)(nil), "types.TMSPInfo")
	proto.RegisterType((*LastBlockInfo)(nil), "types.LastBlockInfo")
	proto.RegisterType((*ConfigInfo)(nil), "types.ConfigInfo")
	proto.RegisterType((*Header)(nil), "types.Header")
	proto.RegisterType((*BlockID)(nil), "types.BlockID")
	proto.RegisterType((*PartSetHeader)(nil), "types.PartSetHeader")
	proto.RegisterType((*Validator)(nil), "types.Validator")
	proto.RegisterEnum("types.MessageType", MessageType_name, MessageType_value)
	proto.RegisterEnum("types.CodeType", CodeType_name, CodeType_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for TMSPApplication service

type TMSPApplicationClient interface {
	Echo(ctx context.Context, in *RequestEcho, opts ...grpc.CallOption) (*ResponseEcho, error)
	Flush(ctx context.Context, in *RequestFlush, opts ...grpc.CallOption) (*ResponseFlush, error)
	Info(ctx context.Context, in *RequestInfo, opts ...grpc.CallOption) (*ResponseInfo, error)
	SetOption(ctx context.Context, in *RequestSetOption, opts ...grpc.CallOption) (*ResponseSetOption, error)
	AppendTx(ctx context.Context, in *RequestAppendTx, opts ...grpc.CallOption) (*ResponseAppendTx, error)
	CheckTx(ctx context.Context, in *RequestCheckTx, opts ...grpc.CallOption) (*ResponseCheckTx, error)
	Query(ctx context.Context, in *RequestQuery, opts ...grpc.CallOption) (*ResponseQuery, error)
	Proof(ctx context.Context, in *RequestProof, opts ...grpc.CallOption) (*ResponseProof, error)
	Commit(ctx context.Context, in *RequestCommit, opts ...grpc.CallOption) (*ResponseCommit, error)
	InitChain(ctx context.Context, in *RequestInitChain, opts ...grpc.CallOption) (*ResponseInitChain, error)
	BeginBlock(ctx context.Context, in *RequestBeginBlock, opts ...grpc.CallOption) (*ResponseBeginBlock, error)
	EndBlock(ctx context.Context, in *RequestEndBlock, opts ...grpc.CallOption) (*ResponseEndBlock, error)
}

type tMSPApplicationClient struct {
	cc *grpc.ClientConn
}

func NewTMSPApplicationClient(cc *grpc.ClientConn) TMSPApplicationClient {
	return &tMSPApplicationClient{cc}
}

func (c *tMSPApplicationClient) Echo(ctx context.Context, in *RequestEcho, opts ...grpc.CallOption) (*ResponseEcho, error) {
	out := new(ResponseEcho)
	err := grpc.Invoke(ctx, "/types.TMSPApplication/Echo", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tMSPApplicationClient) Flush(ctx context.Context, in *RequestFlush, opts ...grpc.CallOption) (*ResponseFlush, error) {
	out := new(ResponseFlush)
	err := grpc.Invoke(ctx, "/types.TMSPApplication/Flush", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tMSPApplicationClient) Info(ctx context.Context, in *RequestInfo, opts ...grpc.CallOption) (*ResponseInfo, error) {
	out := new(ResponseInfo)
	err := grpc.Invoke(ctx, "/types.TMSPApplication/Info", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tMSPApplicationClient) SetOption(ctx context.Context, in *RequestSetOption, opts ...grpc.CallOption) (*ResponseSetOption, error) {
	out := new(ResponseSetOption)
	err := grpc.Invoke(ctx, "/types.TMSPApplication/SetOption", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tMSPApplicationClient) AppendTx(ctx context.Context, in *RequestAppendTx, opts ...grpc.CallOption) (*ResponseAppendTx, error) {
	out := new(ResponseAppendTx)
	err := grpc.Invoke(ctx, "/types.TMSPApplication/AppendTx", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tMSPApplicationClient) CheckTx(ctx context.Context, in *RequestCheckTx, opts ...grpc.CallOption) (*ResponseCheckTx, error) {
	out := new(ResponseCheckTx)
	err := grpc.Invoke(ctx, "/types.TMSPApplication/CheckTx", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tMSPApplicationClient) Query(ctx context.Context, in *RequestQuery, opts ...grpc.CallOption) (*ResponseQuery, error) {
	out := new(ResponseQuery)
	err := grpc.Invoke(ctx, "/types.TMSPApplication/Query", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tMSPApplicationClient) Proof(ctx context.Context, in *RequestProof, opts ...grpc.CallOption) (*ResponseProof, error) {
	out := new(ResponseProof)
	err := grpc.Invoke(ctx, "/types.TMSPApplication/Proof", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tMSPApplicationClient) Commit(ctx context.Context, in *RequestCommit, opts ...grpc.CallOption) (*ResponseCommit, error) {
	out := new(ResponseCommit)
	err := grpc.Invoke(ctx, "/types.TMSPApplication/Commit", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tMSPApplicationClient) InitChain(ctx context.Context, in *RequestInitChain, opts ...grpc.CallOption) (*ResponseInitChain, error) {
	out := new(ResponseInitChain)
	err := grpc.Invoke(ctx, "/types.TMSPApplication/InitChain", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tMSPApplicationClient) BeginBlock(ctx context.Context, in *RequestBeginBlock, opts ...grpc.CallOption) (*ResponseBeginBlock, error) {
	out := new(ResponseBeginBlock)
	err := grpc.Invoke(ctx, "/types.TMSPApplication/BeginBlock", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tMSPApplicationClient) EndBlock(ctx context.Context, in *RequestEndBlock, opts ...grpc.CallOption) (*ResponseEndBlock, error) {
	out := new(ResponseEndBlock)
	err := grpc.Invoke(ctx, "/types.TMSPApplication/EndBlock", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for TMSPApplication service

type TMSPApplicationServer interface {
	Echo(context.Context, *RequestEcho) (*ResponseEcho, error)
	Flush(context.Context, *RequestFlush) (*ResponseFlush, error)
	Info(context.Context, *RequestInfo) (*ResponseInfo, error)
	SetOption(context.Context, *RequestSetOption) (*ResponseSetOption, error)
	AppendTx(context.Context, *RequestAppendTx) (*ResponseAppendTx, error)
	CheckTx(context.Context, *RequestCheckTx) (*ResponseCheckTx, error)
	Query(context.Context, *RequestQuery) (*ResponseQuery, error)
	Proof(context.Context, *RequestProof) (*ResponseProof, error)
	Commit(context.Context, *RequestCommit) (*ResponseCommit, error)
	InitChain(context.Context, *RequestInitChain) (*ResponseInitChain, error)
	BeginBlock(context.Context, *RequestBeginBlock) (*ResponseBeginBlock, error)
	EndBlock(context.Context, *RequestEndBlock) (*ResponseEndBlock, error)
}

func RegisterTMSPApplicationServer(s *grpc.Server, srv TMSPApplicationServer) {
	s.RegisterService(&_TMSPApplication_serviceDesc, srv)
}

func _TMSPApplication_Echo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestEcho)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TMSPApplicationServer).Echo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/types.TMSPApplication/Echo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TMSPApplicationServer).Echo(ctx, req.(*RequestEcho))
	}
	return interceptor(ctx, in, info, handler)
}

func _TMSPApplication_Flush_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestFlush)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TMSPApplicationServer).Flush(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/types.TMSPApplication/Flush",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TMSPApplicationServer).Flush(ctx, req.(*RequestFlush))
	}
	return interceptor(ctx, in, info, handler)
}

func _TMSPApplication_Info_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TMSPApplicationServer).Info(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/types.TMSPApplication/Info",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TMSPApplicationServer).Info(ctx, req.(*RequestInfo))
	}
	return interceptor(ctx, in, info, handler)
}

func _TMSPApplication_SetOption_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestSetOption)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TMSPApplicationServer).SetOption(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/types.TMSPApplication/SetOption",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TMSPApplicationServer).SetOption(ctx, req.(*RequestSetOption))
	}
	return interceptor(ctx, in, info, handler)
}

func _TMSPApplication_AppendTx_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestAppendTx)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TMSPApplicationServer).AppendTx(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/types.TMSPApplication/AppendTx",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TMSPApplicationServer).AppendTx(ctx, req.(*RequestAppendTx))
	}
	return interceptor(ctx, in, info, handler)
}

func _TMSPApplication_CheckTx_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestCheckTx)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TMSPApplicationServer).CheckTx(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/types.TMSPApplication/CheckTx",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TMSPApplicationServer).CheckTx(ctx, req.(*RequestCheckTx))
	}
	return interceptor(ctx, in, info, handler)
}

func _TMSPApplication_Query_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestQuery)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TMSPApplicationServer).Query(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/types.TMSPApplication/Query",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TMSPApplicationServer).Query(ctx, req.(*RequestQuery))
	}
	return interceptor(ctx, in, info, handler)
}

func _TMSPApplication_Proof_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestProof)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TMSPApplicationServer).Proof(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/types.TMSPApplication/Proof",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TMSPApplicationServer).Proof(ctx, req.(*RequestProof))
	}
	return interceptor(ctx, in, info, handler)
}

func _TMSPApplication_Commit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestCommit)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TMSPApplicationServer).Commit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/types.TMSPApplication/Commit",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TMSPApplicationServer).Commit(ctx, req.(*RequestCommit))
	}
	return interceptor(ctx, in, info, handler)
}

func _TMSPApplication_InitChain_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestInitChain)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TMSPApplicationServer).InitChain(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/types.TMSPApplication/InitChain",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TMSPApplicationServer).InitChain(ctx, req.(*RequestInitChain))
	}
	return interceptor(ctx, in, info, handler)
}

func _TMSPApplication_BeginBlock_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestBeginBlock)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TMSPApplicationServer).BeginBlock(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/types.TMSPApplication/BeginBlock",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TMSPApplicationServer).BeginBlock(ctx, req.(*RequestBeginBlock))
	}
	return interceptor(ctx, in, info, handler)
}

func _TMSPApplication_EndBlock_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestEndBlock)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TMSPApplicationServer).EndBlock(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/types.TMSPApplication/EndBlock",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TMSPApplicationServer).EndBlock(ctx, req.(*RequestEndBlock))
	}
	return interceptor(ctx, in, info, handler)
}

var _TMSPApplication_serviceDesc = grpc.ServiceDesc{
	ServiceName: "types.TMSPApplication",
	HandlerType: (*TMSPApplicationServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Echo",
			Handler:    _TMSPApplication_Echo_Handler,
		},
		{
			MethodName: "Flush",
			Handler:    _TMSPApplication_Flush_Handler,
		},
		{
			MethodName: "Info",
			Handler:    _TMSPApplication_Info_Handler,
		},
		{
			MethodName: "SetOption",
			Handler:    _TMSPApplication_SetOption_Handler,
		},
		{
			MethodName: "AppendTx",
			Handler:    _TMSPApplication_AppendTx_Handler,
		},
		{
			MethodName: "CheckTx",
			Handler:    _TMSPApplication_CheckTx_Handler,
		},
		{
			MethodName: "Query",
			Handler:    _TMSPApplication_Query_Handler,
		},
		{
			MethodName: "Proof",
			Handler:    _TMSPApplication_Proof_Handler,
		},
		{
			MethodName: "Commit",
			Handler:    _TMSPApplication_Commit_Handler,
		},
		{
			MethodName: "InitChain",
			Handler:    _TMSPApplication_InitChain_Handler,
		},
		{
			MethodName: "BeginBlock",
			Handler:    _TMSPApplication_BeginBlock_Handler,
		},
		{
			MethodName: "EndBlock",
			Handler:    _TMSPApplication_EndBlock_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "types/types.proto",
}

func init() { proto.RegisterFile("types/types.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 1841 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xb4, 0x58, 0x4b, 0x73, 0xdb, 0xc8,
	0x11, 0x16, 0x25, 0x3e, 0x9b, 0x0f, 0x8d, 0x5a, 0x94, 0x44, 0x33, 0xa9, 0x94, 0x17, 0xd9, 0xcd,
	0x4a, 0x5e, 0x97, 0x9d, 0x92, 0x6b, 0xb7, 0xec, 0x6c, 0x2a, 0x55, 0x96, 0xad, 0x35, 0x55, 0x1b,
	0xdb, 0x0a, 0xac, 0xf5, 0x21, 0x8f, 0x62, 0x41, 0xc4, 0x90, 0x44, 0x44, 0x02, 0x30, 0x30, 0xb0,
	0x29, 0xff, 0x84, 0xfc, 0x91, 0x5c, 0x73, 0x49, 0xe5, 0x94, 0x63, 0x0e, 0x79, 0x3f, 0x7e, 0x49,
	0x7e, 0x42, 0xaa, 0x67, 0x06, 0x4f, 0x81, 0x39, 0x79, 0x2f, 0x28, 0x4c, 0xf7, 0xd7, 0x3d, 0x33,
	0x3d, 0xdd, 0xdf, 0x3c, 0x60, 0x47, 0x5c, 0xfb, 0x3c, 0xbc, 0x2f, 0xbf, 0xf7, 0xfc, 0xc0, 0x13,
	0x1e, 0xd6, 0x64, 0xc3, 0xf8, 0x6f, 0x15, 0x1a, 0x26, 0x7f, 0x13, 0xf1, 0x50, 0xe0, 0x21, 0x54,
	0xf9, 0x64, 0xee, 0x0d, 0x2a, 0xb7, 0x2b, 0x87, 0xed, 0x63, 0xbc, 0xa7, 0xe0, 0x5a, 0x7b, 0x3a,
	0x99, 0x7b, 0xa3, 0x0d, 0x53, 0x22, 0xf0, 0x33, 0xa8, 0x4d, 0x17, 0x51, 0x38, 0x1f, 0x6c, 0x4a,
	0xe8, 0x6e, 0x1e, 0xfa, 0x15, 0xa9, 0x46, 0x1b, 0xa6, 0xc2, 0x90, 0x5b, 0xc7, 0x9d, 0x7a, 0x83,
	0xad, 0x32, 0xb7, 0x67, 0xee, 0x54, 0xba, 0x25, 0x04, 0x3e, 0x04, 0x08, 0xb9, 0x18, 0x7b, 0xbe,
	0x70, 0x3c, 0x77, 0x50, 0x95, 0xf8, 0x83, 0x3c, 0xfe, 0x15, 0x17, 0x2f, 0xa5, 0x7a, 0xb4, 0x61,
	0xb6, 0xc2, 0xb8, 0x81, 0x9f, 0x43, 0xcb, 0xf2, 0x7d, 0xee, 0xda, 0x63, 0xb1, 0x1a, 0xd4, 0xa4,
	0xe1, 0x7e, 0xde, 0xf0, 0xb1, 0x54, 0x5f, 0xac, 0x46, 0x1b, 0x66, 0xd3, 0xd2, 0xff, 0x78, 0x0c,
	0xcd, 0xc9, 0x9c, 0x4f, 0xae, 0xc8, 0xaa, 0x2e, 0xad, 0xf6, 0xf2, 0x56, 0x4f, 0x48, 0x2b, 0x8d,
	0x1a, 0x13, 0xf5, 0x8b, 0xf7, 0xa0, 0x3e, 0xf1, 0x96, 0x4b, 0x47, 0x0c, 0x1a, 0xd2, 0xa2, 0x5f,
	0xb0, 0x90, 0xba, 0xd1, 0x86, 0xa9, 0x51, 0x14, 0xab, 0x37, 0x11, 0x0f, 0xae, 0x07, 0xcd, 0xb2,
	0x58, 0xfd, 0x8c, 0x54, 0x14, 0x2b, 0x89, 0xa1, 0x08, 0x38, 0xae, 0x23, 0xc6, 0x93, 0xb9, 0xe5,
	0xb8, 0x83, 0x56, 0x59, 0x04, 0xce, 0x5c, 0x47, 0x3c, 0x21, 0x35, 0x45, 0xc0, 0x89, 0x1b, 0xf8,
	0x25, 0xb4, 0x2f, 0xf9, 0xcc, 0x71, 0xc7, 0x97, 0x0b, 0x6f, 0x72, 0x35, 0x00, 0x69, 0x3a, 0xc8,
	0x9b, 0x9e, 0x10, 0xe0, 0x84, 0xf4, 0xa3, 0x0d, 0x13, 0x2e, 0x93, 0x16, 0x85, 0x8f, 0x62, 0xa7,
	0x4c, 0xdb, 0x65, 0xe1, 0x3b, 0x75, 0xed, 0xd8, 0xb0, 0xc9, 0xf5, 0x3f, 0x4d, 0xcd, 0x0f, 0x3c,
	0x6f, 0x3a, 0xe8, 0x94, 0x4d, 0xed, 0x9c, 0x54, 0x34, 0x35, 0x89, 0x39, 0x69, 0x40, 0xed, 0xad,
	0xb5, 0x88, 0xb8, 0xf1, 0x29, 0xb4, 0x33, 0x39, 0x85, 0x03, 0x68, 0x2c, 0x79, 0x18, 0x5a, 0x33,
	0x2e, 0x13, 0xaf, 0x65, 0xc6, 0x4d, 0xa3, 0x07, 0x9d, 0x6c, 0x46, 0x19, 0xdd, 0xc4, 0x90, 0xb2,
	0xc6, 0xf8, 0x11, 0xb0, 0x62, 0x52, 0x20, 0x83, 0xad, 0x2b, 0x7e, 0xad, 0x1d, 0xd1, 0x2f, 0xf6,
	0x75, 0xb7, 0x32, 0x55, 0x5b, 0xa6, 0x1e, 0xc3, 0x47, 0xb0, 0x5d, 0xc8, 0x0b, 0xec, 0xc1, 0xa6,
	0x58, 0x49, 0xcb, 0x8e, 0xb9, 0x29, 0x56, 0xc6, 0x6d, 0xe8, 0xe5, 0x93, 0xe0, 0x06, 0xe2, 0xe3,
	0x64, 0x7c, 0x72, 0x15, 0xa9, 0x2b, 0xb5, 0xd2, 0x0a, 0xa2, 0x1a, 0xc6, 0xc3, 0x04, 0x25, 0x03,
	0x92, 0x1d, 0x62, 0x47, 0x0d, 0x71, 0x1f, 0xea, 0x73, 0xee, 0xcc, 0xe6, 0x42, 0x8e, 0x71, 0xcb,
	0xd4, 0x2d, 0x63, 0x1b, 0xba, 0xb9, 0xa4, 0x32, 0x9e, 0x26, 0x33, 0x4e, 0x92, 0x00, 0x7f, 0x08,
	0xf0, 0xd6, 0x5a, 0x38, 0xb6, 0x25, 0xbc, 0x20, 0x1c, 0x54, 0x6e, 0x6f, 0x1d, 0xb6, 0x8f, 0x99,
	0x5e, 0x88, 0xd7, 0xb1, 0xc2, 0xcc, 0x60, 0x8c, 0x17, 0xb0, 0x73, 0x23, 0x1f, 0x10, 0xa1, 0x3a,
	0xb7, 0xc2, 0xb9, 0x1e, 0x96, 0xfc, 0xc7, 0x4f, 0x68, 0x5c, 0x96, 0xcd, 0x03, 0x5d, 0xe6, 0x5d,
	0xed, 0x76, 0x24, 0x85, 0xa6, 0x56, 0x1a, 0x47, 0x49, 0x2c, 0xe3, 0x24, 0xc9, 0xcc, 0x88, 0xfc,
	0x55, 0x93, 0x19, 0xfd, 0xa1, 0x06, 0x4d, 0x93, 0x87, 0xbe, 0xe7, 0x86, 0x1c, 0x1f, 0x42, 0x8b,
	0xaf, 0x26, 0x5c, 0x15, 0x7b, 0xa5, 0x90, 0xaf, 0x0a, 0x73, 0x1a, 0xeb, 0x29, 0xd7, 0x13, 0x30,
	0x1e, 0x69, 0xa2, 0x2a, 0xb2, 0x8f, 0x36, 0xca, 0x32, 0xd5, 0xdd, 0x98, 0xa9, 0xb6, 0x0a, 0xc5,
	0xaa, 0xb0, 0x05, 0xaa, 0x3a, 0xd2, 0x54, 0x55, 0x2d, 0x75, 0x9c, 0xe3, 0xaa, 0x47, 0x39, 0xae,
	0xaa, 0x95, 0x0e, 0x7f, 0x0d, 0x59, 0x7d, 0x91, 0x25, 0xab, 0x7a, 0xa1, 0xc6, 0x95, 0x65, 0x29,
	0x5b, 0x3d, 0xc8, 0xb0, 0x55, 0xa3, 0x50, 0xa4, 0xca, 0xac, 0x84, 0xae, 0xee, 0x27, 0x74, 0xd5,
	0x2c, 0x10, 0x9c, 0x36, 0x29, 0xf2, 0xd5, 0xdd, 0x38, 0x8b, 0x5b, 0xa5, 0x11, 0x2b, 0x10, 0xd6,
	0xa3, 0x1c, 0x61, 0x41, 0x69, 0x18, 0xd6, 0x30, 0xd6, 0x8f, 0xf3, 0x8c, 0xa5, 0x68, 0xe7, 0x56,
	0xc1, 0x76, 0x2d, 0x65, 0x7d, 0x91, 0xa5, 0xac, 0x4e, 0x69, 0x10, 0x4b, 0x39, 0xeb, 0x6e, 0xcc,
	0x59, 0xdd, 0xd2, 0xe9, 0xad, 0x23, 0xad, 0x23, 0x2a, 0x9a, 0x42, 0x52, 0x52, 0xc1, 0xf3, 0x20,
	0xf0, 0x02, 0xcd, 0x37, 0xaa, 0x61, 0x1c, 0x52, 0xc1, 0xa7, 0xa9, 0xf8, 0x7f, 0x08, 0x4e, 0x16,
	0x78, 0x26, 0x11, 0x8d, 0xdf, 0x55, 0x52, 0x5b, 0xca, 0x36, 0x2a, 0x4b, 0x99, 0x90, 0xca, 0x50,
	0x65, 0xde, 0x5d, 0x68, 0x89, 0x65, 0xe8, 0x8f, 0xa5, 0x42, 0x95, 0xc0, 0xb6, 0x9e, 0xc5, 0xc5,
	0xf3, 0x57, 0xe7, 0x64, 0x67, 0x36, 0x09, 0x21, 0x3d, 0x3c, 0x00, 0x58, 0x58, 0xa1, 0xd0, 0x81,
	0xca, 0x57, 0xc1, 0x4f, 0xad, 0x50, 0xc8, 0xa8, 0x48, 0x9b, 0xd6, 0x22, 0x6e, 0xe2, 0x11, 0x25,
	0x8d, 0x3b, 0x75, 0x66, 0xba, 0x12, 0x76, 0xb4, 0xc1, 0x13, 0x29, 0x94, 0x68, 0x0d, 0x30, 0x3e,
	0x49, 0x03, 0x93, 0xa3, 0xe1, 0x85, 0x37, 0x8b, 0x69, 0x78, 0xe1, 0xcd, 0x8c, 0x5f, 0x11, 0x75,
	0xe5, 0x73, 0x1b, 0xbf, 0x0f, 0xd5, 0x89, 0x67, 0xab, 0xa8, 0xf4, 0x92, 0x39, 0x3c, 0xf1, 0x6c,
	0x7e, 0x71, 0xed, 0x73, 0x53, 0x2a, 0x29, 0x02, 0xb6, 0x25, 0x2c, 0x39, 0xd1, 0x8e, 0x29, 0xff,
	0x63, 0xf7, 0x5b, 0xa9, 0xfb, 0x5f, 0x12, 0x07, 0xe5, 0x6a, 0xe0, 0x43, 0x7a, 0xff, 0x79, 0xba,
	0x4e, 0x8a, 0xe9, 0xbf, 0x1d, 0xdf, 0x6a, 0x7f, 0xf8, 0x80, 0xbe, 0x7f, 0x41, 0x5b, 0x58, 0xb6,
	0xcc, 0x3f, 0xa4, 0xf3, 0xdd, 0x74, 0xe1, 0x93, 0x02, 0x37, 0xfa, 0x80, 0x37, 0x2b, 0x57, 0xed,
	0xd4, 0xf9, 0x9a, 0xc4, 0x1f, 0x40, 0xcd, 0x76, 0xa6, 0xd3, 0x70, 0x50, 0x5d, 0xb3, 0x65, 0x29,
	0xb5, 0xf1, 0x31, 0x34, 0xe3, 0xac, 0xa6, 0x4a, 0x7a, 0xcd, 0x83, 0x30, 0xde, 0x2f, 0x5a, 0x66,
	0xdc, 0x34, 0x9e, 0x43, 0x37, 0x97, 0xcc, 0xf8, 0x11, 0x74, 0x64, 0xc6, 0x8f, 0x73, 0xfb, 0x50,
	0x5b, 0xca, 0x46, 0x52, 0x84, 0xb7, 0x80, 0xa8, 0x75, 0x2c, 0xb7, 0x3d, 0x35, 0xd5, 0x86, 0xe5,
	0xfb, 0x23, 0x2b, 0x9c, 0x1b, 0xbf, 0xa9, 0x00, 0xa4, 0xb9, 0x8e, 0xf7, 0xa1, 0xbf, 0xb4, 0x56,
	0xaa, 0x84, 0xc6, 0xa1, 0xf3, 0x9e, 0x8f, 0x2f, 0xaf, 0x05, 0x0f, 0xb5, 0xd3, 0x9d, 0xa5, 0xb5,
	0x92, 0x1d, 0xbf, 0x72, 0xde, 0xf3, 0x13, 0x52, 0xe0, 0x67, 0x80, 0x05, 0x03, 0xb1, 0x0a, 0x65,
	0x27, 0x55, 0x73, 0x3b, 0x0b, 0xbf, 0x58, 0x85, 0xf8, 0x3d, 0x68, 0x13, 0x58, 0xac, 0x24, 0x52,
	0x86, 0xb8, 0x6a, 0xb6, 0x96, 0xd6, 0xea, 0x62, 0x45, 0x10, 0xe3, 0xb7, 0x9b, 0x50, 0x57, 0x5b,
	0x2e, 0x0d, 0x59, 0x12, 0xed, 0xd8, 0xb1, 0xe3, 0x08, 0xc8, 0xf6, 0x99, 0x5d, 0x38, 0x44, 0x24,
	0x5b, 0x2e, 0x2d, 0xa6, 0x70, 0x96, 0xb1, 0x5b, 0xf9, 0x8f, 0x07, 0xd0, 0x70, 0xa3, 0xa5, 0x1c,
	0x53, 0x55, 0x81, 0xdd, 0x68, 0x49, 0x43, 0x39, 0x86, 0x6e, 0x4a, 0x16, 0xd4, 0x89, 0xda, 0xd7,
	0x7a, 0x7a, 0x71, 0x54, 0x78, 0x9f, 0x9a, 0xed, 0x84, 0x29, 0xce, 0x6c, 0x3c, 0x04, 0x26, 0x6d,
	0xd4, 0xf6, 0xa1, 0xc2, 0x59, 0x97, 0xe1, 0xec, 0x91, 0x5c, 0xef, 0x2f, 0x74, 0x9e, 0xf8, 0x0e,
	0xb4, 0x28, 0x97, 0x14, 0xa4, 0x21, 0x21, 0x4d, 0x12, 0x48, 0xe5, 0xa7, 0xb0, 0x9d, 0x9e, 0x51,
	0x14, 0xa4, 0xa9, 0xbc, 0xa4, 0x62, 0x09, 0xcc, 0x2e, 0x5b, 0x2b, 0xbf, 0x6c, 0x67, 0xd0, 0xd0,
	0x43, 0x2c, 0x3d, 0xcf, 0xdc, 0x81, 0x9a, 0x6f, 0x05, 0x22, 0xd4, 0xa4, 0x19, 0xb3, 0xe0, 0xb9,
	0x15, 0xd0, 0x09, 0x52, 0x9f, 0x6a, 0x14, 0xc4, 0x78, 0x04, 0xdd, 0x9c, 0x9c, 0xb8, 0x5e, 0x78,
	0xc2, 0x5a, 0xe8, 0x45, 0x57, 0x8d, 0xa4, 0x9b, 0xcd, 0xb4, 0x1b, 0xe3, 0x11, 0xb4, 0x92, 0x2c,
	0xa6, 0x65, 0xf1, 0xa3, 0xcb, 0xaf, 0x93, 0x03, 0x9f, 0x6e, 0x91, 0x3b, 0xdf, 0x7b, 0xa7, 0x8f,
	0x56, 0x55, 0x53, 0x35, 0xee, 0xfc, 0xa9, 0x02, 0xed, 0xe7, 0x6a, 0x73, 0xa0, 0x7a, 0xc4, 0x6d,
	0x68, 0xbf, 0x88, 0x16, 0x0b, 0x2d, 0x62, 0x1b, 0xd8, 0x84, 0x2a, 0xed, 0x29, 0xac, 0x82, 0x2d,
	0xa8, 0xc9, 0x3d, 0x83, 0x6d, 0x92, 0x90, 0xd2, 0x94, 0x6d, 0x61, 0x17, 0x5a, 0x09, 0x09, 0xb3,
	0x2a, 0x35, 0x93, 0xcd, 0x8a, 0xd5, 0xb0, 0x03, 0xcd, 0x98, 0x7b, 0xd9, 0x0e, 0xb6, 0xa1, 0xa1,
	0xa9, 0x92, 0x21, 0x02, 0xd4, 0xd5, 0x42, 0xb1, 0x5d, 0xf2, 0x2c, 0x59, 0x8e, 0xf5, 0xc9, 0x41,
	0x52, 0xdb, 0x6c, 0x0f, 0x7b, 0x00, 0x69, 0x55, 0xb3, 0x7d, 0x72, 0x18, 0xd7, 0x33, 0x3b, 0x20,
	0x3b, 0xc9, 0x60, 0x6c, 0x70, 0xe7, 0xf7, 0x35, 0x68, 0xc6, 0xa4, 0x82, 0x75, 0xd8, 0x7c, 0xf9,
	0x35, 0xdb, 0xc0, 0x1d, 0xe8, 0x9e, 0xb9, 0x82, 0x07, 0xae, 0xb5, 0x38, 0xa5, 0x8d, 0x92, 0x55,
	0x48, 0x74, 0xea, 0x4e, 0x3c, 0xdb, 0x71, 0x67, 0x4a, 0xb4, 0x49, 0x3e, 0x4f, 0x2c, 0xfb, 0x85,
	0xe7, 0x4e, 0x38, 0xdb, 0x42, 0x06, 0x9d, 0x6f, 0x5c, 0x2b, 0x12, 0x73, 0x2f, 0x70, 0xde, 0x73,
	0x9b, 0x55, 0x71, 0x0f, 0x76, 0xce, 0xdc, 0x30, 0x9a, 0x4e, 0x9d, 0x89, 0xc3, 0x5d, 0xf1, 0x55,
	0xe4, 0xda, 0x21, 0xab, 0x21, 0x42, 0xef, 0x1b, 0xf7, 0xca, 0xf5, 0xde, 0xb9, 0xfa, 0x2c, 0xca,
	0xea, 0x38, 0x80, 0xfe, 0x89, 0x15, 0xf2, 0xa7, 0x91, 0xbf, 0x70, 0x26, 0x96, 0xe0, 0x8f, 0x6d,
	0x3b, 0xe0, 0x61, 0xc8, 0x38, 0x39, 0x21, 0x4d, 0xbe, 0xef, 0x69, 0x6c, 0x90, 0xf3, 0xcf, 0x79,
	0xc8, 0x66, 0x78, 0x0b, 0xf6, 0x6e, 0x68, 0x64, 0xcf, 0x73, 0xfc, 0x2e, 0x0c, 0x8a, 0xaa, 0x67,
	0x56, 0x78, 0x1e, 0x38, 0x13, 0xce, 0x1c, 0xec, 0x03, 0x53, 0x5a, 0x99, 0xc5, 0x67, 0xae, 0x1f,
	0x09, 0xf6, 0xeb, 0xb8, 0x7f, 0x2d, 0x7d, 0x19, 0x09, 0x12, 0x5f, 0x15, 0xc4, 0xe7, 0x32, 0x53,
	0xd8, 0x02, 0x0f, 0x60, 0x37, 0x23, 0x7e, 0x45, 0xf3, 0xa3, 0xe8, 0x2c, 0xd3, 0xf1, 0x2a, 0x85,
	0x33, 0x73, 0x2d, 0x11, 0x05, 0x9c, 0xb9, 0xb8, 0x0f, 0x48, 0x1a, 0x1d, 0x92, 0x78, 0xe2, 0x5e,
	0xdc, 0x83, 0x96, 0xeb, 0x1e, 0xfc, 0xa2, 0x78, 0x11, 0xcd, 0x1c, 0x97, 0xbd, 0xc1, 0x3d, 0x60,
	0xcf, 0xbc, 0xb7, 0x5a, 0x7a, 0xea, 0x0a, 0x47, 0x5c, 0xb3, 0x3f, 0x57, 0xb0, 0x0f, 0xdb, 0xa9,
	0xf8, 0x59, 0xe0, 0x45, 0x3e, 0xfb, 0x4b, 0x05, 0x0f, 0x00, 0x53, 0xe9, 0x79, 0xe0, 0xf9, 0x5e,
	0x68, 0x2d, 0xd8, 0x5f, 0x2b, 0xb8, 0x0f, 0x3b, 0xcf, 0xbc, 0xb7, 0xc9, 0x2a, 0x28, 0x83, 0xbf,
	0xc5, 0x06, 0x89, 0xfc, 0x39, 0x5f, 0x5e, 0xf2, 0x80, 0xfd, 0xbd, 0x82, 0xb7, 0xa0, 0x9f, 0x55,
	0x24, 0xbe, 0xfe, 0x51, 0xd1, 0x23, 0x4a, 0x54, 0xaf, 0x3d, 0xc1, 0xd9, 0x3f, 0x63, 0xb1, 0x8e,
	0x83, 0x76, 0xf4, 0xaf, 0x0a, 0xee, 0x42, 0x2f, 0x15, 0x4b, 0xec, 0xbf, 0x2b, 0x38, 0x84, 0xbd,
	0x9c, 0xd0, 0x71, 0x67, 0xe7, 0x54, 0x7c, 0xec, 0x3f, 0x95, 0xe3, 0x3f, 0xd6, 0x60, 0x9b, 0x76,
	0x9b, 0xc7, 0xbe, 0xea, 0x80, 0xce, 0x32, 0xf7, 0x55, 0xc9, 0x61, 0xc9, 0x7b, 0xc8, 0xb0, 0xec,
	0xea, 0x81, 0xc7, 0xba, 0x32, 0xb1, 0xec, 0x59, 0x64, 0x58, 0x7a, 0x03, 0xa1, 0x4e, 0xd4, 0x79,
	0xef, 0xe6, 0xeb, 0xc8, 0xb0, 0xec, 0x1a, 0x82, 0x3f, 0xc9, 0x54, 0x3a, 0xae, 0x7b, 0x23, 0x19,
	0xae, 0xbd, 0x90, 0xe0, 0x97, 0x29, 0x17, 0xe0, 0x9a, 0x97, 0x92, 0xe1, 0xba, 0x4b, 0x09, 0x3e,
	0x4c, 0xa8, 0x03, 0xcb, 0xdf, 0x4b, 0x86, 0x6b, 0x2e, 0x26, 0x14, 0x1b, 0x75, 0x82, 0x2a, 0x7b,
	0x06, 0x19, 0x96, 0xde, 0x35, 0xc8, 0x46, 0x9d, 0x8c, 0xca, 0xde, 0x17, 0x86, 0xa5, 0x07, 0x78,
	0xfc, 0x3c, 0xe6, 0x33, 0x2c, 0x7d, 0x9e, 0x19, 0x96, 0xdf, 0x82, 0x28, 0xaa, 0xe9, 0xcd, 0x7a,
	0xdd, 0xbb, 0xcb, 0x70, 0xed, 0xfd, 0x06, 0x1f, 0x67, 0x09, 0x12, 0xd7, 0xbe, 0xbe, 0x0c, 0xd7,
	0xdf, 0x72, 0x68, 0x61, 0xd2, 0x6b, 0x74, 0xf9, 0x1b, 0xcc, 0x70, 0xdd, 0x45, 0xe7, 0xb2, 0x2e,
	0xdf, 0xf6, 0x1e, 0xfc, 0x2f, 0x00, 0x00, 0xff, 0xff, 0x15, 0xb7, 0xd3, 0xb5, 0xf0, 0x13, 0x00,
	0x00,
}
